defaults: &defaults
  starling:
    server: localhost:16020
    queue: provisioning_queue

  memcached:
    server: localhost:11211
    key:
      cpus: provisioning_cpus
      monitor: provisioning_monitor
      state: provisioning_state

  monitor_caches: 50

  max_cpus: 16
  min_memory: 512
  max_memory: 4096

  storage:
    server: stoiw-grp02
    account: shigitani
    password: 69H96Cb5
    chap_user: vmconnector
    allow_ipaddress: 172.29.*.*

  pools_for_instance:
    - backup-pool02

  physical_server:
    - zone: Iwamizawa
      physical_servers:
        - pmiw-kvm018
        - pmiw-kvm019

  virtual_server:
    centos:
      account: root
      password: iwroot

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
