defaults: &defaults
  starling:
    server: localhost:16020
    queue: provisioning_queue

  memcached:
    server: localhost:11211
    key:
      cpus: provisioning_cpus
      monitor: provisioning_monitor

  monitor_caches: 50

  virtual_server:
    centos:
      account: root
      password: ******


development:
  <<: *defaults

  max_cpus: 16
  min_memory: 512
  max_memory: 4096

  storage:
    server: storage-server01
    confirm_on_operation: true
    account: devuser
    password: *******
    chap_user: vmconnector
    allow_ipaddress: 172.25.*.*

  pools_for_instance:
    - development-pool01

  physical_server:
    - zone: Iwamizawa
      physical_servers:
        - physical_server001
        - physical_server002
        - physical_server003


production:
  <<: *defaults

  max_cpus: 16
  min_memory: 1024
  max_memory: 16384

  storage:
    server: storage-server01
    confirm_on_operation: false
    account: prouser
    password: *******
    chap_user: vmconnector
    allow_ipaddress: 172.25.*.*

  pools_for_instance:
    - instance-pool01
    - instance-pool02
    - instance-pool03

  physical_server:
    - zone: Iwamizawa
      physical_servers:
        - physical_server001
        - physical_server002
        - physical_server003
        - physical_server004
        - physical_server005
        - physical_server006
        - physical_server007
        - physical_server008
        - physical_server009
        - physical_server010
        - physical_server011
        - physical_server012
        - physical_server013
        - physical_server014
        - physical_server015
        - physical_server016
        - physical_server017
        - physical_server018
        - physical_server019
        - physical_server020
        - physical_server021
        - physical_server022
